variables:
  UV_CACHE_DIR: .uv-cache
  UV_LINK_MODE: copy

default:
  image: ghcr.io/astral-sh/uv:0.7-python3.13-bookworm-slim
  cache: &uv_cache
    key:
      prefix: uv
      files:
        - uv.lock
    paths:
      - $UV_CACHE_DIR

mypy:
  cache:
    - <<: *uv_cache
    - key: mypy
      paths:
        - .mypy_cache/
  script:
    - uv run mypy --strict --output=json src tests | uv run --group ci mypy-gitlab-code-quality > mypy-gitlab.json
  artifacts:
    reports:
      codequality:
        - mypy-gitlab.json

Ruff:
  script:
    - uv run ruff format --check --diff
    - uv run ruff check --output-format=gitlab > ruff-gitlab.json
  artifacts:
    reports:
      codequality:
        - ruff-gitlab.json

Pylint:
  script:
    - uv run --group ci pylint --output=pylint-gitlab.json --load-plugins=pylint_gitlab --output-format=gitlab-codeclimate sioscgi tests
  artifacts:
    reports:
      codequality:
        - pylint-gitlab.json

Unit tests:
  script:
    - uv run python -m unittest
