"Code style":
  image:
    name: "cytopia/pycodestyle:latest"
    entrypoint: [""]
  script:
    - pycodestyle

"Unit tests":
  image: "python:3-alpine"
  script:
    - pip install .
    - python -m unittest
