image: "python:3-alpine"

"Code style":
  cache:
    paths:
      - .cache/pip
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  script:
    - pip install pycodestyle
    - pycodestyle

"Unit tests":
  script:
    - pip install .
    - python -m unittest
