"mypy":
  image:
    name: "hawk7777/mypy:latest"
    entrypoint: [""]
  cache:
    paths:
      - .mypy_cache/
    key: "mypy"
  script:
    - mypy --strict src

"pycodestyle":
  image:
    name: "cytopia/pycodestyle:latest"
    entrypoint: [""]
  script:
    - pycodestyle

"Pylint":
  image:
    name: "cytopia/pylint:latest"
    entrypoint: [""]
  script:
    - pip3 install -e .
    - pylint sioscgi tests

"Unit tests":
  image: "python:3-alpine"
  script:
    - pip install -e .
    - python -m unittest
