"mypy":
  image:
    name: "grktsh/mypy:latest"
    entrypoint: [""]
  cache:
    paths:
      - .mypy_cache/
    key: "mypy"
  script:
    - mypy --strict src

"pycodestyle":
  image:
    name: "cytopia/pycodestyle:latest"
    entrypoint: [""]
  script:
    - pycodestyle

"Pylint":
  image:
    name: "cytopia/pylint:latest"
    entrypoint: [""]
  script:
    - python -m pip install --disable-pip-version-check -e .
    - pylint sioscgi tests

"Unit tests":
  image: "python:3-alpine"
  script:
    - pip install --disable-pip-version-check -e .
    - python -m unittest
