"mypy":
  image:
    name: "cytopia/mypy:latest"
    entrypoint: [""]
  cache:
    paths:
      - .mypy_cache/
    key: "mypy"
  script:
    - mypy --strict src tests

"Ruff":
  image:
    name: "pipelinecomponents/ruff:0.10.0"
    entrypoint: [""]
  script:
    - ruff format --check --diff
    - ruff check --output-format=gitlab > ruff-gitlab.json
  artifacts:
    reports:
      codequality:
        - ruff-gitlab.json

"Pylint":
  image:
    name: "cytopia/pylint:latest"
    entrypoint: [""]
  script:
    - python -m pip install --disable-pip-version-check -e .
    - pylint sioscgi tests

"Unit tests":
  image: "python:3-alpine"
  script:
    - pip install --disable-pip-version-check -e .
    - python -m unittest
